mkkernel: format making scripts and pack zImage with dtb
Change-Id: Iee8453d38c8e357474862539668165ad8f291918

diff --git a/mkkernel b/mkkernel
--- a/mkkernel
+++ b/mkkernel
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash -e
 
 LOCALPATH=$(pwd)
 ROOTDIR=$(dirname $(dirname $(readlink -f $0)))
@@ -9,45 +9,46 @@ DEFCONFIG=""
 DTB=""
 KERNELIMAGE=""
 
-if [ $# != 1 ] ; then 
-BOARD=kylin
+finish() {
+    echo -e "\e[31m MAKE KERNEL IMAGE FAILED.\e[0m"
+    exit -1
+}
+trap finish ERR
+
+if [ $# != 1 ] ; then
+    BOARD=kylin
 fi
 
 KERNELIMAGE=${IMAGE}/${BOARD}-kernel.img
 
-if [ ! -d ${OUT} ];then
-mkdir ${OUT}
-fi
-
-if [ ! -d ${IMAGE} ];then
-mkdir ${IMAGE}
-fi
+[ ! -d ${OUT} ] && mkdir ${OUT}
+[ ! -d ${IMAGE} ] && mkdir ${IMAGE}
 
 case ${BOARD} in
-	"kylin")
-		DEFCONFIG=rk3036_kylin_linux_defconfig
-		DTB=rk3036-kylin.dtb
-	;;
-	"firefly")
-		DEFCONFIG=""
-		DTB=rk3288-firefly.dtb
-	;;
-	"rk3036evb")
-		DEFCONFIG=""
-		DTB=rk3036-evb.dtb
-	;;
-	*)
-	echo "board not support in kernel"
-	;;
+    "kylin")
+        DEFCONFIG=rk3036_kylin_linux_defconfig
+        DTB=rk3036-kylin.dtb
+        ;;
+    "firefly")
+        DEFCONFIG=""
+        DTB=rk3288-firefly.dtb
+        ;;
+    "rk3036evb")
+        DEFCONFIG=""
+        DTB=rk3036-evb.dtb
+        ;;
+    *)
+        echo "board '${BOARD}' not supported!"
+        return
+        ;;
 esac
+
 echo Building kernel for ${BOARD} board!
 echo Using ${DEFCONFIG}
 
 cd ${ROOTDIR}/kernel
-make ARCH=arm CROSS_COMPILE=arm-linux-gnueabi- O=../out/kernel ${DEFCONFIG}
-make ARCH=arm CROSS_COMPILE=arm-linux-gnueabi- O=../out/kernel
-cd ${OUT}/kernel
-cat arch/arm/boot/zImage arch/arm/boot/dts/${DTB} > kernel.img
-mkimage -A arm -O linux -T kernel -C none -a 0x60000000 -e 0x60000000 -d kernel.img ${KERNELIMAGE}
+make ARCH=arm CROSS_COMPILE=arm-linux-gnueabi- O=${OUT}/kernel ${DEFCONFIG}
+make ARCH=arm CROSS_COMPILE=arm-linux-gnueabi- O=${OUT}/kernel -j8
+cat ${OUT}/kernel/arch/arm/boot/zImage ${OUT}/kernel/arch/arm/boot/dts/${DTB} > ${KERNELIMAGE}
 cd ${LOCALPATH}
-echo Kernel Image: ${KERNELIMAGE}
+echo Kernel zImage with dtb appended: ${KERNELIMAGE}
