Set password of root as 'rockchip'
Change-Id: I5d571b211a4078f347a1f34d8bc1c8e3fc01ed59

diff --git a/mkrootfs b/mkrootfs
--- a/mkrootfs
+++ b/mkrootfs
@@ -1,6 +1,5 @@
-#!/bin/sh
+#!/bin/bash -e
 
-LOCALPATH=$(pwd)
 ROOTDIR=$(dirname $(dirname $(readlink -f $0)))
 OUT=${ROOTDIR}/out
 IMAGE=${ROOTDIR}/image
@@ -19,51 +18,43 @@ ROOTFSIMAGE=${BOARD}-rootfs.img
 
 echo Making rootfs for ${BOARD} board!
 
-if [ ! -d ${OUT} ];then
-    mkdir ${OUT}
-fi
+# Create directories
+for dir in ${OUT} ${IMAGE} ${ROOTFSOUT} ${MOUNTPOINT}; do
+    if [ ! -d ${dir} ]; then
+        mkdir -p ${dir}
+    fi
+done
 
-if [ ! -d ${IMAGE} ];then
-    mkdir ${IMAGE}
-fi
-
-if [ ! -d ${ROOTFSOUT} ];then
-    mkdir ${ROOTFSOUT}
-fi
-
-if [ ! -d ${MOUNTPOINT} ];then
-    mkdir ${MOUNTPOINT}
-fi
-
-if [ ! -f ${ROOTFSOUT}/${DOWNLOADFILE} ];then
+while [ ! -f ${ROOTFSOUT}/${DOWNLOADFILE} -o ${DOWNLOADFILE_CHECKSUM}x \
+          != $(sha1sum ${ROOTFSOUT}/${DOWNLOADFILE} | cut -d' ' -f1)x ]; do
     curl ${DOWNLOADPATH}/${DOWNLOADFILE} > ${ROOTFSOUT}/${DOWNLOADFILE}
-fi
-
-if [ ${DOWNLOADFILE_CHECKSUM} != $(sha1sum ${ROOTFSOUT}/${DOWNLOADFILE} | cut -d' ' -f1) ]; then
-    echo "file checksum mismatch: ${ROOTFSOUT}/${DOWNLOADFILE}"
-    echo "delete ${ROOTFSOUT}/${DOWNLOADFILE} and try again"
-    return
-fi
+done
 
 dd if=/dev/zero of=${IMAGE}/${ROOTFSIMAGE} bs=1M count=300
+
+finish() {
+    sudo umount ${MOUNTPOINT} || true
+    echo -e "\e[31m MAKE ROOTFS FAILED.\e[0m"
+    exit -1
+}
 
 echo Format rootfs to ext4
 mkfs.ext4 ${IMAGE}/${ROOTFSIMAGE}
 
 echo Mount rootfs to ${MOUNTPOINT}
 sudo mount ${IMAGE}/${ROOTFSIMAGE} ${MOUNTPOINT}
+trap finish ERR
 
 echo Extract image to ${MOUNTPOINT}
 sudo tar -xpzf ${ROOTFSOUT}/${DOWNLOADFILE} -C ${MOUNTPOINT}
 
-echo Create user and password
-PASSWORD="rockchip" RKPASSWD=$(perl -e 'print crypt($ARGV[0], "sa-ubuntu")' $PASSWORD)
-sudo useradd --root ${MOUNTPOINT} -s '/bin/bash' -m rockchip -p $RKPASSWD
+PASSWD=$(perl -e 'print crypt($ARGV[0], "nothing")' "rockchip")
+sudo sed -i "s/root:.:/root:$PASSWD:/" ${MOUNTPOINT}/etc/shadow
 
 echo Copy overlay files
 sudo cp -r ${ROOTDIR}/build/overlay/* ${MOUNTPOINT}/
 
 echo Umount rootfs
 sudo umount ${MOUNTPOINT}
-cd ${LOCALPATH}
+
 echo Rootfs Image: ${IMAGE}/${ROOTFSIMAGE}
